import './global.css'

export const metadata = {
  title: 'ごめんなさい投稿祭 公式HP',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body>{children}</body>
    </html>
  )
}
